### ISSUE TITLE
Refactor VocPub requirements

### ISSUE THREAD

**Issue by dr-shorthair** [surroundaustralia/vocpub-profile#4]
Several of the [VocPub profile requirements](https://raw.githack.com/surroundaustralia/vocpub-profile/master/specification.html) are actually compounds. 
This is shown by the fact that the [SHACL implementation](https://raw.githack.com/surroundaustralia/vocpub-profile/master/validator.shacl.ttl) has two or more shapes for some rules, e.g. numbered Requirement-2.1.4a Requirement-2.1.4b. 
Maybe refactor the [requirements](https://github.com/surroundaustralia/vocpub-profile/blob/master/specification.html) to reflect the way they must be implemented?

**Comment by nicholascar** [comment]
I may accept this - will review properly tomorrow - but I don't think it necissary that the Requirements:Shapes rules is 1:1 since a. you can write SHACL rules in different ways, compounding tests or not, and b. Requirements shouldn't be shackled (!) to SHACL: we don't want to force SHACL groupthink onto what we actually requirem fo our vocabs. There are also some Requirements, perhaps for other LD resources, that aren't SHACL-able e.g. things have to be online in HTML & RDF etc.

**Comment by dr-shorthair** [comment]
Yes I agree about SHACL lens or groupthink. But when I see '... and... respectively ...' inside a requirement, I suspect it could be usefully refactored. The SHACL solution merely corroborates this.
